Bump non-gtk dependencies to latest versions
sprang/marmoset pull request #1
Opened 2023-07-15 02:37 UTC by jelmer

Bump non-gtk dependencies to latest versions

2023-09-27 02:13 UTC, jelmer commented
ping @sprang

2024-02-29 22:10 UTC, sprang requested changes
Thanks for updating all these dependencies! Just a few issues to resolve.

2024-02-29 22:10 UTC, sprang commented on examples/genpng.rs
> +    let classic_colors = matches.get_flag("CLASSIC");
This doesn't seem to be handling command line arguments correctly. If I specify a directory I get a panic. Maybe it worked when you first made the changes (the version range for 'clap' in Cargo.toml is quite broad)?

2024-02-29 22:10 UTC, sprang commented on examples/simulate.rs
> +    let games_default = pretty_print(NUM_GAMES).to_string();
_games_default_ appears to be unused.

2024-02-29 22:10 UTC, sprang commented on examples/simulate.rs
> +        .unwrap_or(&num_cpus::get());
Something doesn't seem to be working here. I can't adjust the number of games or threads from the command line.

2024-02-29 22:10 UTC, sprang commented on src/core/graphics.rs
> +        let y = rect.width();
This introduced a rendering bug. Should be:
```
        let x = rect.x();
        let y = rect.y();
```

2024-02-29 22:10 UTC, sprang commented on src/main.rs
> +            if let Some(action) = controller.undo_action_name() {
Indention is wonky here.

2024-04-10 23:34 UTC, jelmer commented
PTAL - I believe these should all be fixed now.

2024-07-29 22:30 UTC, jelmer reviewed
ping :)

2024-12-21 19:20 UTC, merged

2024-12-21 19:58 UTC, sprang commented
Thank you! Sorry it took me a while to pay attention to this.